### ISSUE TITLE
Big problem :(

### ISSUE THREAD

**Issue by RoboTricker** [RoboTricker/Transport-Pipes#11]
In MC 1.10 the client doesn't send a right-click-air event to the server, therefore if you rightclick on a pipe and not look on a block at the same time, the server does not recognizes that...
During MC 1.8 this was working fine... does anybody know any solution?

**Comment by sgdc3** [comment]
interact event?

**Comment by RoboTricker** [comment]
doens't fire on right click air anymore... I already checked the interact packet with protocollib but the server doesn't receive any packets on right-click-air anymore.

**Comment by sgdc3** [comment]
it sounds strange

**Comment by RoboTricker** [comment]
yeah :(
by now there is no way to detect a player right click air.

**Comment by jdkeke142** [comment]
Mhh, the client not send packet right click air uniquely if player not have item in hand. But in your plugin the player have item in hand, simply remove your ignorecancelled and its work.

**Comment by RoboTricker** [comment]
Until 1.9 all worked fine with an item in hand but with 1.10 and above it doenst, did you test it with 1.10?
