### ISSUE TITLE
[Enhancement] Colored pipes

### ISSUE THREAD

**Issue by Dyllaann** [RoboTricker/Transport-Pipes#19]
I'd like to suggest a new feature for the plugin.
It would require quite some work, but I guess it will pay-off in the end.

It's about coloring pipes.
Crafting recipe = pipe + colored glass = new colored pipe.
Using colored pipes will down-scale systems because colored pipes don't connect to other colors.
Colored pipes only connect to the same colors, or blank pipes.

This will making compact systems alot easier, since input and output pipes can be next to eachother, yet they can't connect.
Plus, It helps maintaining your system. People on my server have started getting creative with their builds (http://prntscr.com/f7uq17), but they are losing focus on what each line is doing.

By guessing you place a glass block on an armor-stand which displays the pipe, i think it shouldn't be that hard to make the texture (Change the glass block to colored glass), just the actual logic behind it might require quite some work.

I hope you understand what I am talking about, if not: please let me know and I'll try to explain it using pictures.
I love this plugin and I'd like to see it evolve!

**Comment by RoboTricker** [comment]
Great idea! I actually struggled myself with maintaining complex pipe structures, but I haven't thought of this solution. I'm going to implement the feature as soon as possible.

**Comment by RoboTricker** [comment]
With the last commit, I added colored pipes support.

colored pipes can be crafted with an pipe item and the specific dye item (bone meal for white pipes, lapis for blue pipes, etc.). Colored pipes don't connect to different colored pipes but all colors connect to iron and golden pipes.

You can test the new version here: [http://jenkins.frontfight.net/job/Transport-Pipes/](http://jenkins.frontfight.net/job/Transport-Pipes/)
