### ISSUE TITLE
1.8 Support: is it possible?

### ISSUE THREAD

**Issue by sgdc3** [RoboTricker/Transport-Pipes#2]
> You won't get this working on 1.8 because in MC 1.8 there is no "Marker tag" and without that the pipes have a hitbox. Therefore the placing and breaking of them is a big issue.

How do you use the marker tag?

**Comment by RoboTricker** [comment]
`byte bitMask = (byte) ((asd.isSmall() ? 0x01 : 0x00) | 0x04 | 0x08 | 0x10); //(small) + hasArms + noBasePlate + Marker` 

This is in the class ArmorStandProtocol and it enables the marker tag. With the marker tag enabled the pipe armor stands haven't got an entity hitbox therefore I can easily handle a click onto the block behind. You can remove this marker tag and see what it does :/

If you press f3 + h I think you can see the hitbox of the armorstand (in gamemode 3)

**Comment by RoboTricker** [comment]
Can I close this issue or do you have any idea to avoid the marker tag problem?

**Comment by sgdc3** [comment]
I stopped working on that, i updated all my servers to 1.11.2.
