### ISSUE TITLE
Add FactionUUID support

### ISSUE THREAD

**Issue by sgdc3** [RoboTricker/Transport-Pipes#21]
Hello, i once asked for faction support but in the meantime i switched to FactionUUID, could you implement an hook?

**Comment by RoboTricker** [comment]
yeah of course, give me some time :)

**Comment by RoboTricker** [comment]
ehm, I can't access the API because the plugin costs 15 USD :/

**Comment by RoboTricker** [comment]
could you test if FactionsUUID support works with the last commit?

**Comment by sgdc3** [comment]
Whoops, sorry, yeah it seems to work fine. Thank you ;)
