### ISSUE TITLE
Spigot 1.12 PrepareItemCraftEvent NullPointerException

### ISSUE THREAD

**Issue by Dyllaann** [RoboTricker/Transport-Pipes#22]
Don't know how to replicate, but playing on 1.12 creates this error.
I guess it has to do with the new recipe book or something. You know where to find me to test it.

//EDIT: The log is very hard to read on Github.
Screenshot of log: http://prntscr.com/fi8pn6
Pastebin of log: https://pastebin.com/BFasjHd0

**Comment by RoboTricker** [comment]
I will try to fix this, thanks ;)

**Comment by RoboTricker** [comment]
ok I found the bug. It's fixed with commit 69e2ea4
