### ISSUE TITLE
Block TransportPipes in certain worlds and AcidIsland /purge support

### ISSUE THREAD

**Issue by ScuroK** [RoboTricker/Transport-Pipes#37]
Hey. I would like to ask for a option in the config called: "disabled worlds:".
Because i didnt find any way to disable the plugin in certain worlds. Giving negative permission on crafting didnt work for me. i was still able to craft and place pipes.

Also i am wondering what happens with pipes on a plot if this plot gets clearen. or on a skyblock island if it gets deleted?

btw i made a small donation. keep up the good work!

EDIT: Crafting permissions DO work. It was because i am OP thats why i bypassed it. Sorry for this.

**Comment by RoboTricker** [comment]
the latest jenkins build has now a config option called "disabled_worlds" where you can specify the worlds for which TransportPipes should be blocked.
