### ISSUE TITLE
Pipes Do Not Break When Full

### ISSUE THREAD

**Issue by PhasecoreX** [RoboTricker/Transport-Pipes#39]
I have max_items_per_pipe set to 10 in my config file (the default amount), however it seems as though the pipes do not break. I have 512 items running in a 4 pipe square to test this, and no pipes are breaking automatically.

![2018-01-29_21 32 57](https://user-images.githubusercontent.com/10203357/35545309-7445dc84-053c-11e8-9fd5-7e265b4f3e3a.png)

I am running Paper version git-Paper-1317 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT), and am using the latest plugin as of a day ago (v4.3.0-b70). There are no errors in the log pertaining to this.

**Comment by RoboTricker** [comment]
I reimplemented this feature in the lastest dev version: http://jenkins.frontfight.net/job/TransportPipes/73/artifact/target/transportpipes-4.3.1-SNAPSHOT.jar Should work fine :)

**Comment by PhasecoreX** [comment]
Looks good to me! Pipes explode as expected now.
