### ISSUE TITLE
Deprecated Recipe Creation

### ISSUE THREAD

**Issue by PhasecoreX** [RoboTricker/Transport-Pipes#40]
I get several warnings in the server logs when TransportPipes starts up, complaining about using a deprecated method to create recipes. It says to "Please ask the author to give their recipe a static key using NamespacedKey."

Here's an excerpt from the logs: [https://pastebin.com/V7aZnPVs](https://pastebin.com/V7aZnPVs)

I am running Paper version git-Paper-1317 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT), and am using the latest plugin as of a day ago (v4.3.0-b70).

**Comment by RoboTricker** [comment]
This issue should be fixed in the latest dev version: http://jenkins.frontfight.net/job/TransportPipes/73/artifact/target/transportpipes-4.3.1-SNAPSHOT.jar

**Comment by PhasecoreX** [comment]
Looks good to me! No more exceptions in the logs.
