### ISSUE TITLE
Tpipes problem 4.3.0 v

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [RoboTricker/Transport-Pipes#41]
Hey man, how are you?

I just downloaded your latest DEV relase right now. Now is 12:31 of 30/01/18
Your DEV build il completely broken, so I tried to download the spigot "stable" version. But it is broken too.

What is the problem?
The texture pack. It automatically download his own resourcepack, also if I put Vanilla rendersystem.
I have my own texture pack set with RPGInventory plugin, I tried to put tpipes textures on it with the new dev version of tpipes.

But the texture has difficulties to load.

So I'm litterally obliged to deupgrade your version and use the 4.2.2.

Now everything works.
My own texture has been downloaded and I'm using vanilla rendering system, cos the modelled one doesn't work if we use custom textures because your plugin doesn't support RPGInventory.

Minecraft version 1.12.2
Thanks in advance

**Comment by RoboTricker** [comment]
Ok, so you can change the resourcepack config option to "server", therefore TransportPipes will assume that you have merged the RPGInventory resourcepack and the TransportPipes resourcepack into one pack and put the link to that in the server-resourcepack option inside the server.properties. You can read about this in the wiki: https://github.com/RoboTricker/Transport-Pipes/wiki/Settings

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I tried putting server and none too.
But this doesn't work with the latest DEV build.

I surely will try this with the 4.2.2 version.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Problem putting "server" is that your plugin will take infos in minecraft.properties... but the resource link is set in the config file of RPGInventory

**Comment by RoboTricker** [comment]
with "server", TransportPipes will just assumes that the resourcepack will be given to the player anyway else then through TransportPipes itself. But you can try to delete the folder server-resource-packs inside your .minecraft folder try it again.

**Comment by Dreadonator** [comment]
Yeah „server“ is a great option!

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Still not close this thicket please, I will test it as soon as possible.
