### ISSUE TITLE
Permissions-Bug

### ISSUE THREAD

**Issue by ScuroK** [RoboTricker/Transport-Pipes#44]
Hey i havefound a bug in latest version:

Players cant craft the crafting pipe so i chexked my persmissions file. I found they dont have any crafting-permissions. But they can can craft colored pipes. so how comes they dont need a persmission for them but need one for the crafting pipe?

Right now they only have negative transportpipes.* in certain worlds.

**Comment by ScuroK** [comment]
not sure if its because i did negative .3 persmissions for some worlds. luckperms is a bit weird in this things. im testing.

**Comment by RoboTricker** [comment]
Alright, thanks for the bug report. The issue should be fixed in this build: http://jenkins.frontfight.net/job/TransportPipes/lastSuccessfulBuild/artifact/target/transportpipes-4.3.2-SNAPSHOT.jar

**Comment by ScuroK** [comment]
oh thx alot!
 i test it out now

**Comment by ScuroK** [comment]
It works! thx alot!

**Comment by ScuroK** [comment]
@RoboTricker Leider muss ich trotzdem für jede deaktivierte welt das craften verbieten. weil craften geht trotzdem, auch wenn die welt in der config disabled ist. naja istt nicht so schlimm :D
