### ISSUE TITLE
Placing a Pipe in the same block as another Pipe turns it into a Head

### ISSUE THREAD

**Issue by BlackBeltPanda** [RoboTricker/Transport-Pipes#48]
Using TransportPipes Version 4.3.2-SNAPSHOT-b72 on Paper version git-Paper-1414 (MC: 1.12.2)

If you place a pipe under an existing pipe, but in the same block space, it places a head which, when broken, does not drop a pipe.

GIF: https://i.gyazo.com/c7534840964b6d7ccc49d761f5c3eb60.gif

**Comment by RoboTricker** [comment]
Thank you for this detailed bug report (thats not natural :smile:)

I've planned to recode the hole plugin this summer which will definitely fix this issue. So please be Patient :)

**Comment by BlackBeltPanda** [comment]
I forked the repo and made a quick change which blocks placing skulls in the same block space as ducts. It's quick and dirty but gets the job done, though I had to fight a bit with GitHub to get the commit up without it thinking I changed every line. XD

So I'm satisfied for now. Can't wait for the recode! =)
