### ISSUE TITLE
[Suggestion] Add events to the API for inserting and extracting items

### ISSUE THREAD

**Issue by BlackBeltPanda** [RoboTricker/Transport-Pipes#49]
Adding events for inserting and extracting items to the API makes it much easier to integrate plugins with pipes. For example, I have containers that perform actions only when an item is inserted into them. If I could add a listener for something like a DuctInsertEvent, that would allow me to make those containers compatible with Transport Pipes.

**Comment by RoboTricker** [comment]
Hm ok, but are these containers custom containers of yours? If so it should be pretty easy for you to notify yourself about such an event :) But yeah I will keep that in mind when I recode the plugin this summer :)

**Comment by BlackBeltPanda** [comment]
Just things like dispensers, droppers, chests, etc.
