### ISSUE TITLE
Pipes stop working if i walk away and  come back

### ISSUE THREAD

**Issue by sgdc3** [RoboTricker/Transport-Pipes#9]
If i walk away (many chunks) and come.bavk pipes are visible but they stop working.

**Comment by sgdc3** [comment]
@RoboTricker Do you have any idea about that?

**Comment by RoboTricker** [comment]
I couldn't reproduce this issue on my own. Do you have any more detailed information?

**Comment by RoboTricker** [comment]
Do you can check if this bug is fixed with the last commit? I couldn't reproduce the bug myself but maybe you can.

**Comment by sgdc3** [comment]
I'll try again in latest builds, this report is outdated.
